fix handle timeout error
ice-lab/iceworks pull request #795
Opened 2021-02-26 08:57 UTC by fyangstudio

修复宏任务的回调函数中的错误无法捕获，导致上层调用 try catch 无效。

修改为 微任务 错误回调，上层可 catch doctor 所有错误

2021-03-01 02:13 UTC, alvinhui commented on packages/doctor/src/Timer.ts
> +      setTimeout(resolve, ms);
没有赋值给 `this.timer` ？下面那个 clearTimeout 永远不会执行了。

2021-03-01 02:15 UTC, alvinhui requested changes
看看上面的问题

2021-03-02 02:30 UTC, fyangstudio commented on packages/doctor/src/Timer.ts
> +      setTimeout(resolve, ms);
外层是 promise race，一个执行完即可。  这里不影响，保险起见 这个我还是加上好了

2021-03-02 03:09 UTC, alvinhui approved these changes

2021-03-02 06:03 UTC, alvinhui approved these changes

2021-03-02 07:50 UTC, merged